import { SuperHeroModel } from './superhero.model';

export const superHeroSingleMock: SuperHeroModel = {
  id: 2,
  name: 'Abe Sapien',
  fullName: 'Abraham Sapien',
  height: '191 cm',
  weight: '65 kg',
  power: 100,
  strength: 28,
  speed: 35,
  images:
    'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/2-abe-sapien.jpg',
};

export const superHeroMock: SuperHeroModel[] = [
  {
    id: 1,
    name: 'A-Bomb',
    fullName: 'Richard Milhouse Jones',
    height: '203 cm',
    weight: '441 kg',
    power: 24,
    strength: 100,
    speed: 17,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg',
  },
  {
    id: 2,
    name: 'Abe Sapien',
    fullName: 'Abraham Sapien',
    height: '191 cm',
    weight: '65 kg',
    power: 100,
    strength: 28,
    speed: 35,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/2-abe-sapien.jpg',
  },
  {
    id: 3,
    name: 'Abin Sur',
    fullName: '',
    height: '185 cm',
    weight: '90 kg',
    power: 99,
    strength: 90,
    speed: 53,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/3-abin-sur.jpg',
  },
  {
    id: 4,
    name: 'Abomination',
    fullName: 'Emil Blonsky',
    height: '203 cm',
    weight: '441 kg',
    power: 62,
    strength: 80,
    speed: 53,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/4-abomination.jpg',
  },
  {
    id: 5,
    name: 'Abraxas',
    fullName: 'Abraxas',
    height: '0 cm',
    weight: '0 kg',
    power: 100,
    strength: 63,
    speed: 83,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/5-abraxas.jpg',
  },
  {
    id: 6,
    name: 'Absorbing Man',
    fullName: 'Carl Creel',
    height: '193 cm',
    weight: '122 kg',
    power: 98,
    strength: 80,
    speed: 25,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/6-absorbing-man.jpg',
  },
  {
    id: 7,
    name: 'Adam Monroe',
    fullName: '',
    height: '0 cm',
    weight: '0 kg',
    power: 100,
    strength: 10,
    speed: 12,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/7-adam-monroe.jpg',
  },
  {
    id: 8,
    name: 'Adam Strange',
    fullName: 'Adam Strange',
    height: '185 cm',
    weight: '88 kg',
    power: 37,
    strength: 10,
    speed: 33,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/8-adam-strange.jpg',
  },
  {
    id: 10,
    name: 'Agent Bob',
    fullName: 'Bob',
    height: '178 cm',
    weight: '81 kg',
    power: 5,
    strength: 8,
    speed: 13,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/10-agent-bob.jpg',
  },
  {
    id: 11,
    name: 'Agent Zero',
    fullName: 'Christoph Nord',
    height: '191 cm',
    weight: '104 kg',
    power: 72,
    strength: 28,
    speed: 38,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/11-agent-zero.jpg',
  },
  {
    id: 12,
    name: 'Air-Walker',
    fullName: 'Gabriel Lan',
    height: '188 cm',
    weight: '108 kg',
    power: 100,
    strength: 85,
    speed: 100,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/12-air-walker.jpg',
  },
  {
    id: 13,
    name: 'Ajax',
    fullName: 'Francis',
    height: '193 cm',
    weight: '90 kg',
    power: 34,
    strength: 48,
    speed: 35,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/13-ajax.jpg',
  },
  {
    id: 14,
    name: 'Alan Scott',
    fullName: 'Alan Ladd Wellington Scott',
    height: '180 cm',
    weight: '90 kg',
    power: 100,
    strength: 80,
    speed: 23,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/14-alan-scott.jpg',
  },
  {
    id: 15,
    name: 'Alex Mercer',
    fullName: 'Alexander J. Mercer',
    height: '0 cm',
    weight: '0 kg',
    power: 100,
    strength: 80,
    speed: 42,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/15-alex-mercer.jpg',
  },
  {
    id: 17,
    name: 'Alfred Pennyworth',
    fullName: 'Alfred Thaddeus Crane Pennyworth',
    height: '178 cm',
    weight: '72 kg',
    power: 7,
    strength: 10,
    speed: 17,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/17-alfred-pennyworth.jpg',
  },
  {
    id: 18,
    name: 'Alien',
    fullName: 'Xenomorph',
    height: '244 cm',
    weight: '169 kg',
    power: 57,
    strength: 28,
    speed: 42,
    images:
      'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/18-alien.jpg',
  },
];
